FROM node:16-alpine AS builder
WORKDIR /app

RUN apk update && apk add --no-cache git

COPY /ui/react/package.json ./
RUN file="$(node -v)" && echo $file

RUN npm install 

COPY /ui/react/ .

RUN npm install ajv@latest ajv-keywords@latest --save

ARG BUILD_VERSION=1.0.0.0
ARG BUILD_ENVIRONMENT=ci

RUN npm run build:dev

FROM nginx:alpine
COPY /ui/react/nginx.conf /etc/nginx/nginx.conf

COPY --from=builder /app/build/ /usr/share/nginx/html/